# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Project
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # build in preperation for CI
      - run:
          name: Build Scripts
          command: npm run build:scripts

      # run tests!
      - run:
          name: Test Project
          command: npm test

      # create Code Coverage Artifacts
      - run:
          name: Create Code Coverage Artifacts
          command: |
            mkdir -p /tmp/coverage
            cp coverage/* /tmp/coverage


      # copy Cover to artifacts
      - store_artifacts:
          path: /tmp/coverage

      # integrate with CodeCov
      - run:
          name: Commit to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
